service: lambda-spring

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-central-1
  memorySize: 384
  timeout: 20
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  environment:
    DYNAMODB_TABLE: Book
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  artifact: target/lambda-spring.jar

functions:
  api:
    handler: de.serverlessbuch.spring.LambdaHandler
    events:
      - http:
          path: /{proxy+}
          method: any
          private: true
