package de.serverlessbuch.spring.books;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * @author Niko Köbler, http://www.n-k.de, @dasniko
 */
@Data
@DynamoDBTable(tableName = "Book")
public class Book {
    @DynamoDBHashKey
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String author;
    @DynamoDBAttribute
    private String url;
    @DynamoDBAttribute
    private String twitter;
}
